use_frameworks!

target 'CircularControl_Example' do
  pod 'CircularControl', :path => '../'

  target 'CircularControl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
